# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('M', 'Mens'), ('F', 'Women'), ('k', 'kIDS')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AD', 'Addidas'), ('NK', 'Nike'), ('CV', 'Coverse'), ('DD', 'Diadora'), ('EA', 'Emporium Armani'), ('NB', 'New Balance'), ('PM', 'Puma')], default='', max_length=2),
        ),
    ]
