# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200519_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
