# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200519_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('M', 'Mens'), ('F', 'Women'), ('k', 'kids')], default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('AD', 'Addidas'), ('NK', 'Nike'), ('CV', 'Coverse'), ('DD', 'Diadora'), ('EA', 'Emporium Armani'), ('NB', 'New Balance'), ('PM', 'Puma')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
