# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200520_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AD', 'Addidas'), ('NK', 'Nike'), ('CV', 'Coverse'), ('DD', 'Diadora'), ('EA', 'Emporium Armani'), ('NB', 'New Balance'), ('PM', 'Puma')], default='AD', max_length=20),
        ),
    ]
