# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200523_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='history_of_product',
            new_name='history_of_product_1',
        ),
        migrations.AddField(
            model_name='product',
            name='history_of_product_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='history_of_product_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='history_of_product_4',
            field=models.TextField(blank=True),
        ),
    ]
