# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200523_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_3',
        ),
    ]
